codecov:
  notify:
    after_n_builds: 1

coverage:
  status:
    project:
      default:
        target: 95%
    patch:
      default:
        target: 90%

ignore:
  - "**/tests/**"
  - "**/tests.rs"
  - "**/test_utils/**"
